### ISSUE TITLE
doesnt work in AndroidStudio 3 with 3.0.0-alpha1 android gradle plugin

### ISSUE THREAD

**Issue by rburgst** [seadowg/deckard-kotlin#5]
If you upgrade the gradle android plugin to 3.0.0-alpha1
```
buildscript {
    ext.kotlin_version = '1.1.2-4'

    repositories {
        jcenter()
        maven { url 'https://maven.google.com' }
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0-alpha1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
```

then running the test within IntelliJ will lead to 

```
Class not found: "com.example.test.DeckardActivityTest"Empty test suite.
```

**Comment by seadowg** [comment]
@rburgst is this still a problem with the newer 3.0.0 plugin?

**Comment by rburgst** [comment]
Now it looks slightly better:

```

java.lang.RuntimeException: java.lang.NullPointerException

	at org.robolectric.res.ResourceTableFactory.parseResourceFiles(ResourceTableFactory.java:155)
	at org.robolectric.res.ResourceTableFactory.newResourceTable(ResourceTableFactory.java:43)
	at org.robolectric.res.ResourceMerger.buildResourceTable(ResourceMerger.java:22)
	at org.robolectric.RobolectricTestRunner.getAppResourceTable(RobolectricTestRunner.java:450)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:288)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:203)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
Caused by: java.lang.NullPointerException
	at org.robolectric.res.DocumentLoader.loadFile(DocumentLoader.java:35)
	at org.robolectric.res.DocumentLoader.load(DocumentLoader.java:26)
	at org.robolectric.res.ResourceTableFactory.loadOpaque(ResourceTableFactory.java:166)
	at org.robolectric.res.ResourceTableFactory.parseResourceFiles(ResourceTableFactory.java:142)
	... 24 more


Process finished with exit code 255
```

**Comment by rburgst** [comment]
note that I upgraded to alpha-3

```
buildscript {
    ext.kotlin_version = '1.1.2-4'

    repositories {
        jcenter()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0-alpha3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "io.realm:realm-gradle-plugin:3.3.1"
    }
}
...
```

**Comment by rburgst** [comment]
might be related to https://github.com/robolectric/robolectric/issues/3169

**Comment by rburgst** [comment]
tried 1.1.2-5 and alpha4, still no joy 
```
buildscript {
    ext.kotlin_version = '1.1.2-5'

    repositories {
        jcenter()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0-alpha4'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
```


Error is still the resource loading issues.

```

java.lang.RuntimeException: java.lang.NullPointerException

	at org.robolectric.res.ResourceTableFactory.parseResourceFiles(ResourceTableFactory.java:155)
	at org.robolectric.res.ResourceTableFactory.newResourceTable(ResourceTableFactory.java:43)
	at org.robolectric.res.ResourceMerger.buildResourceTable(ResourceMerger.java:22)
	at org.robolectric.RobolectricTestRunner.getAppResourceTable(RobolectricTestRunner.java:450)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:288)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:203)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
Caused by: java.lang.NullPointerException
	at org.robolectric.res.DocumentLoader.loadFile(DocumentLoader.java:35)
	at org.robolectric.res.DocumentLoader.load(DocumentLoader.java:26)
	at org.robolectric.res.ResourceTableFactory.loadOpaque(ResourceTableFactory.java:166)
	at org.robolectric.res.ResourceTableFactory.parseResourceFiles(ResourceTableFactory.java:142)
	... 24 more
```

in robolectric/robolectric#3169 there is talk about disabling `aapt2` but I dont know how to do that nor do I think its useful since many libraries require annotation processing.

**Comment by CCorrado** [comment]
Having the same issue on my project, running AS 3.0 Canary 4 gradle 3.0.0-alpha4 / gradle-4.0-rc-1.

Disabling aapt2 as a workaround would break libraries like dagger/butterknife that generate view binder classes etc (and for sure the unit tests depend on these libraries for binding views in fragments)

I was holding out a bit on my project to upgrade to AS 3.0 until API 26 hit production. I guess I could switch over to AS 2.3.3 and wait it out until 3.0 hits production :)

`java.lang.RuntimeException: java.lang.NullPointerException

	at org.robolectric.res.ResourceTableFactory.parseResourceFiles(ResourceTableFactory.java:155)
	at org.robolectric.res.ResourceTableFactory.newResourceTable(ResourceTableFactory.java:43)
	at org.robolectric.res.ResourceMerger.buildResourceTable(ResourceMerger.java:22)
	at org.robolectric.RobolectricTestRunner.getAppResourceTable(RobolectricTestRunner.java:450)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:288)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:203)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
Caused by: java.lang.NullPointerException
	at org.robolectric.res.DocumentLoader.loadFile(DocumentLoader.java:35)
	at org.robolectric.res.DocumentLoader.load(DocumentLoader.java:26)
	at org.robolectric.res.ResourceTableFactory.parseResourceFiles(ResourceTableFactory.java:140)
	... 32 more
`

**Comment by seadowg** [comment]
@rburgst Yeah looks like a very similar problem. I'll keep an eye on the the Robolectric issue and leave this open for now.

I know it's not great but it probably makes sense to stay on 2.x tooling right now.
